# Generated by Django 4.1 on 2023-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "OPEN"),
                    ("closed", "CLOSED"),
                    ("withdrew", "WITHDREW"),
                ],
                default="open",
                max_length=100,
            ),
        ),
    ]
