# Generated by Django 4.1 on 2023-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_type_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("py", "Python programming"),
                    ("cpp", "C++ programming"),
                    ("mldl", "ML/DL"),
                    ("django", "django web development"),
                    ("study", "Studying"),
                    ("trade", "Trading"),
                    ("fluid", "Fluid dynamics"),
                    ("thermodynamics", "Thermodynamics"),
                    ("maths", "Mathematics"),
                    ("ices", "ICEs"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("py", "Python programming"),
                    ("cpp", "C++ programming"),
                    ("mldl", "ML/DL"),
                    ("django", "django web development"),
                    ("study", "Studying"),
                    ("trade", "Trading"),
                    ("fluid", "Fluid dynamics"),
                    ("thermodynamics", "Thermodynamics"),
                    ("maths", "Mathematics"),
                    ("ices", "ICEs"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
    ]
